### ISSUE TITLE
Add option to download with “Multi-threads” [Feature Request]

### ISSUE THREAD

**Issue by ghost** [clpo13/wikiget#3]
Currently, the Python script seems very slow to download numerous files (Manjaro KDE).

I have a list of 730,000 pronunciations to download from the German Wiktionary: 
https://commons.wikimedia.org/wiki/User_talk:Jeuwre#Method_to_download_all_%22Jeuwre%22_audios_on_Commons

 If such a large list is run with a single terminal, the process is eternal. The bandwidth consumed is around 20 Kb/s despite having a download speed of 700 Kb/s.

A workaround is to split a large .csv/.txt in small files. Then, open "20" terminal windows and run them simultaneously. However, it is very time-consuming because any error interrupts all the process, and they require “manual” restart.

**Would it be possible to add an option of “multithreading” as to query and download many files simultaneously (e.g. 20) ?**

----------------
_Thanks for your great job ! Your code has been really helpful for me :smiley: I am downloading the Pronunciations from German Wiktionary to make an offline pronunciation .mdx dictionary for [GoldenDict](https://en.wikipedia.org/wiki/GoldenDict) (freely available)._

**Comment by clpo13** [comment]
I'm glad to hear you've found it useful! Adding threaded downloading was definitely on my to-do list. If I remember correctly, I had actually started experimenting with that not long after I added batch downloading, so I'll see if I can get it working soon.

**Comment by hugolpz** [comment]
LinguaLibre is interested by this feature as well.
We have about 130 categories and 700,000 tiny audio files to handle, Wikiget seems a great avenue to create monthly dumps.
